export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_COMPANIES = "GET_COMPANIES";
export const GET_ALLPRODUCTS = "GET_ALLPRODUCTS";
export const GETTOKENACCESS = "GETTOKENACCESS";
export const GETTOKENPROFILEINFO = "GETTOKENPROFILEINFO";
export const GET_RECENT_ORDER = "GET_RECENT_ORDER";
export const GET_VISA_CARDS_DETAILS = "GET_VISA_CARDS_DETAILS";
